### ISSUE TITLE
Customizable Subfolder Group Tree 

### ISSUE THREAD

**Issue by jjlmoya** [Malvid/Malvid#48]
**Feature request:**
Will be interesting extend group functionality for customize subfolders

**Alternatives considered**
Read subfolders and create dynamically the structure.

**Comment by electerious** [comment]
I've used subfolders in Fractal and I really didn't like them because they added a lot of clutter and made finding the right component hard. One level of groups should be enough to cover most cases. It forces you to keep it simple.

But I'm open for ideas, so any design and implementation suggestion is welcome.

**Comment by emsuiko** [comment]
We're using subfolders in our src-directory b/c we wanted to group the components there as well (not only visually in the Malvid UI).
Looks something like this:
```
src
- components
-- group1
--- componentA
--- componentB
-- group2
--- componentC
...
```

The directory structure Malvid needs to build the UI is generated in a temporary directory through the gulp-task. That is combining template+data to the HTML for the iframe as well.

@jjlmoya Hope this helps. Depends on how/when you're running malvid of course.

**Comment by electerious** [comment]
Sub-Folders won't make it into Malvid. I would prefer a pages feature as suggested by @extrabright: https://github.com/Malvid/Malvid/issues/75
